CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  is_active BOOLEAN NOT NULL,
  is_archive BOOLEAN NOT NULL DEFAULT FALSE,
)