name: vicly-basic-pipeline

on:
  push:
    branches: [ master, develop ]

  pull_request:
    branches: [ master, develop ]

jobs:
  checkfmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v5
        
      - name: Format check
        run: sbt scalafmtCheck

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v5
        
      - name: Run tests & coverage
        run: sbt clean coverage test coverageReport
